// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDYQdpu7a_sEa3MWsuE72P4MCbOTMCqZk',
    appId: '1:324240485670:web:4fcc06e4d41a3a8132e5e7',
    messagingSenderId: '324240485670',
    projectId: 'fir-authen-77ffe',
    authDomain: 'fir-authen-77ffe.firebaseapp.com',
    storageBucket: 'fir-authen-77ffe.appspot.com',
    measurementId: 'G-4261R925BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByyrLgGGm7rVE2q4fvX4wAYZqHt7fBqSU',
    appId: '1:324240485670:android:6c9102cfd97d2d9132e5e7',
    messagingSenderId: '324240485670',
    projectId: 'fir-authen-77ffe',
    storageBucket: 'fir-authen-77ffe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBosat7HIDAy3Rz_bPdXaL9LO4WBcuqbjg',
    appId: '1:324240485670:ios:681d6c16c2a8e4a132e5e7',
    messagingSenderId: '324240485670',
    projectId: 'fir-authen-77ffe',
    storageBucket: 'fir-authen-77ffe.appspot.com',
    iosBundleId: 'com.example.firebaseauthen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBosat7HIDAy3Rz_bPdXaL9LO4WBcuqbjg',
    appId: '1:324240485670:ios:681d6c16c2a8e4a132e5e7',
    messagingSenderId: '324240485670',
    projectId: 'fir-authen-77ffe',
    storageBucket: 'fir-authen-77ffe.appspot.com',
    iosBundleId: 'com.example.firebaseauthen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDYQdpu7a_sEa3MWsuE72P4MCbOTMCqZk',
    appId: '1:324240485670:web:96ea826cd0e2b40132e5e7',
    messagingSenderId: '324240485670',
    projectId: 'fir-authen-77ffe',
    authDomain: 'fir-authen-77ffe.firebaseapp.com',
    storageBucket: 'fir-authen-77ffe.appspot.com',
    measurementId: 'G-K4PG4SWS6Z',
  );
}
